Repository hmcts/ccd-case-document-am-api, pull requests merged in 2021-12, with the labels that each got.

#504 CCD-2260: Add FPL case service to CDAM
  charts/ccd-case-document-am-api/Chart.yaml
  charts/ccd-case-document-am-api/values.yaml
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-504

#506 CCD-2312: Temporarily disable Fortify Scan in nightly build
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-506

#507 update log4j
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-507

#505 CCD-2170: Add FR update role
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-505

#509 CCD-2231-update-cve-suppression-dates-dec-2021
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-509

#510 CCD-2374: Update log4j version to 2.17.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-510

#511 CCD-2377: Adding PRL service to service_config.json in case-document-am-api
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-511
