Repository hmcts/ccd-case-document-am-api, pull requests merged in 2021-03, with the labels that each got.

#369 RDM-11001 - FT fixes for error response.
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/ccd/documentam/befta/CaseDocumentApiBeftaRunner.java
  src/functionalTest/resources/features/F-001/F-001.feature
  src/functionalTest/resources/features/F-001/S-002.td.json
  src/functionalTest/resources/features/F-001/S-003.td.json
  src/functionalTest/resources/features/F-001/S-004.td.json
  src/functionalTest/resources/features/F-001/S-110.td.json
  src/functionalTest/resources/features/F-001/S-111.td.json
  src/functionalTest/resources/features/F-001/S-112.td.json
  src/functionalTest/resources/features/F-002/F-002.feature
  src/functionalTest/resources/features/F-002/S-021.td.json
  src/functionalTest/resources/features/F-002/S-022.td.json
  src/functionalTest/resources/features/F-002/S-023.td.json
  src/functionalTest/resources/features/F-002/S-114.td.json
  src/functionalTest/resources/features/F-002/S-115.td.json
  src/functionalTest/resources/features/F-002/S-116.td.json
  src/functionalTest/resources/features/F-003/F-003_Get_Document_with_404.td.json
  src/functionalTest/resources/features/F-003/S-033.td.json
  src/functionalTest/resources/features/F-003/S-034.td.json
  src/functionalTest/resources/features/F-003/S-126.td.json
  src/functionalTest/resources/features/F-003/S-127.td.json
  src/functionalTest/resources/features/F-003/S-128.td.json
  src/functionalTest/resources/features/F-004/S-041.td.json
  src/functionalTest/resources/features/F-004/S-042.td.json
  src/functionalTest/resources/features/F-004/S-043.td.json
  src/functionalTest/resources/features/F-004/S-044.td.json
  src/functionalTest/resources/features/F-004/S-045.td.json
  src/functionalTest/resources/features/F-004/S-046.td.json
  src/functionalTest/resources/features/F-004/S-118.td.json
  src/functionalTest/resources/features/F-004/S-119.td.json
  src/functionalTest/resources/features/F-004/S-120.td.json
  src/functionalTest/resources/features/F-005/S-051.td.json
  src/functionalTest/resources/features/F-005/S-052.td.json
  src/functionalTest/resources/features/F-005/S-053.td.json
  src/functionalTest/resources/features/F-005/S-054.td.json
  src/functionalTest/resources/features/F-005/S-055.td.json
  src/functionalTest/resources/features/F-005/S-122.td.json
  src/functionalTest/resources/features/F-005/S-123.td.json
  src/functionalTest/resources/features/F-005/S-124.td.json
  src/functionalTest/resources/features/F-006/S-062.td.json
  src/functionalTest/resources/features/F-006/S-063.td.json
  src/functionalTest/resources/features/F-006/S-106.td.json
  src/functionalTest/resources/features/F-006/S-107.td.json
  src/functionalTest/resources/features/F-006/S-108.td.json
  src/functionalTest/resources/features/F-007/S-071.td.json
  src/functionalTest/resources/features/F-007/S-072.td.json
  src/functionalTest/resources/features/F-007/S-073.td.json
  src/functionalTest/resources/features/F-007/S-074.td.json
  src/functionalTest/resources/features/F-007/S-075.td.json
  src/functionalTest/resources/features/F-007/S-076.td.json
  src/functionalTest/resources/features/F-007/S-102.td.json
  src/functionalTest/resources/features/F-007/S-103.td.json
  src/functionalTest/resources/features/F-007/S-104.td.json
  src/functionalTest/resources/features/common/error/AM_400_Response.td.json
  src/functionalTest/resources/features/common/error/AM_403_Response.td.json
  src/functionalTest/resources/features/common/error/AM_404_Response.td.json
  src/functionalTest/resources/features/common/error/AM_500_Response.td.json
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/controller/advice/CaseDocumentControllerAdvice.java
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/exception/ResourceNotFoundException.java
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-369

#376 Revert "RDM-11454 fix CVE-2021-22112 +(use hmcts plugin)"
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-376

#375 RDM-11001 - fixed swagger publisher and Integration setup
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/config/SwaggerPublisher.java
  src/integrationTest/resources/integration-test.properties
  src/integrationTest/resources/wiremock-stubs/idam/openid_config.json
  src/test/java/uk/gov/hmcts/reform/ccd/documentam/TestIdamConfiguration.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-375

#382 RDM-11001 - terraform cleanup
  infrastructure/.terraform-version
  infrastructure/README.md
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-382

#383 RDM-11001 - terraform cleanup
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-383

#385 RDM-11454 CCD Case Document AM API
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-385

#386 RDM-11416 - Rename env vars to match those specified in ccd-docker
  Jenkinsfile_CNP
  README.md
  charts/ccd-case-document-am-api/Chart.yaml
  charts/ccd-case-document-am-api/values.aat.template.yaml
  charts/ccd-case-document-am-api/values.preview.template.yaml
  charts/ccd-case-document-am-api/values.yaml
  docker-compose.yml
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Case_Creation_Base_Data.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Default_Full_Case_Creation_Data.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Default_Full_Case_Response_Single_Document.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Default_Full_Case_With_Single_Document.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Default_Token_Creation_Data_For_Case_Creation.td.json
  src/main/resources/application.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-386

#392 RDM-11765 Update CVE Suppress Until Date In All Services
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-392

#393 RDM-11783 Fix Broken Master Build
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/ccd/documentam/befta/CaseDocumentAmTestAutomationAdapter.java
  src/functionalTest/java/uk/gov/hmcts/ccd/documentam/befta/TestDataLoaderMain.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-393

#395 RDM-11831 Fix alternate Failures Case Doc AM Master Build
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-395
