Repository hmcts/ccd-case-document-am-api, pull requests merged in 2022-10, with the labels that each got.

#600 CCD 3658 CVE 2022 25857 fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-600

#607 added suppression
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-607

#606 CCD-3532-3533: Added fix for CVE-2022-22970 CVE-2022-22971 CVE-2022-42003 and CVE-2022-42004
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-606

#608 CCD-3773 Conditionally cleanup helm releases on PRs
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-608, keep-helm
