Repository hmcts/ccd-case-document-am-api, pull requests merged in 2022-05, with the labels that each got.

#551 additional logs for debugging
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/client/dmstore/DocumentStoreClient.java
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
  src/main/resources/application.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-551

#537 implemented patch metadata operation into generate hashtoken flow
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/DocumentManagementService.java
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImplTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-537

#553 add READ permission to ccd_data
  src/functionalTest/resources/features/F-001/F-001.feature
  src/functionalTest/resources/features/F-002/F-002.feature
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-553

#547 CCD-2972: Fortify vulnerabilities fix
  src/functionalTest/resources/features/common/case/Citizen_Full_Case_Creation_Data.td.json
  src/functionalTest/resources/features/common/case/Citizen_Token_Creation_Data_For_Case_Creation.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Citizen_Case_Creation_Data.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Citizen_Token_Creation_Data.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Token_For_Update_Case.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation_by_solicitor_1/Befta_Jurisdiction2_Default_Full_Case_Creation_Data_solicitor_1.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation_by_solicitor_1/Befta_Jurisdiction2_Default_Token_Creation_Data_For_Case_Creation_Solicitor_1.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-citizen-case-creation/Befta_Jurisdiction2_Default_Citizen_Case_Creation_Data.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-citizen-case-creation/Befta_Jurisdiction2_Default_Token_Creation_Data_For_Citizen_Case_Creation.td.json
  src/functionalTest/resources/features/common/case/befta_new/Befta_Default_Full_Case_Creation_Data.td.json
  src/functionalTest/resources/features/common/case/befta_new/Befta_Default_Token_Creation_Data_For_Case_Creation.td.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-547

#554 suppression of CVE-2016-1000027 and until date extension for current …
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-554

#555 suppression of CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-555

#556 suppression of CVE-2022-22970,CVE-2022-22971
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-556

#557 CVE-2016-1000027 is noted as false positive
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-557

#559 CVE-2022-29885: ccd-case-document-am-api fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-559

#558 Removed suppressions and updated spring-framework.version to 5.3.20
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-558

#563 added fis_cos_api service configurations
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-563
