Repository hmcts/ccd-case-document-am-api, pull requests merged in 2022-02, with the labels that each got.

#522 CCD-2543: Ignore Fortify scan results
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-522

#523 Suppressing CVE-2021-22060 with added notes
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-523

#526 CVE-2021-22060, CVE-2022-23181, CVE-2021-42550, CVE-2021-44832 fixes …
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-526

#528 CWE-862 Suppression
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-528

#530 Amend Suppression Dates
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-530

#531 helm chart update
  charts/ccd-case-document-am-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-531
