Repository hmcts/ccd-case-document-am-api, pull requests merged in 2022-09, with the labels that each got.

#596 Suppress CVE-2022-25857 in suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-596

#595 Ccd 3577 cleanup CVE suppressions
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-595

#599 CCD-3682 Suppressions for snakeyaml CVE-2022-38751 CVE-2022-38750 CVE…
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-599

#597 CCD-3427 CVE-2022-34305 tomcat upgrade to 9.0.65, suppression removed
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-597

#587 CCD-3509 CVE-2021-22044 springCloud version upgraded from 3.0.1 to 3.…
  Dockerfile
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/configuration/SwaggerConfigurationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/wiremock/WireMockTestConfiguration.java
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/configuration/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/security/JwtGrantedAuthoritiesConverter.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/ccd/documentam/security/JwtGrantedAuthoritiesConverterTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-587

#598 CCD-3643 Create renovate.json
  .github/renovate.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-598

#583 CCD-3539 : Stop running Nightly builds on weekends
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-583

#602 CCD-3712 - add case type BAIL to iac
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-602

#586 Remove ccd version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-586

#605 CCD-3736: Suppress CVE-2022-38752
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-605
