Repository hmcts/ccd-case-document-am-api, pull requests merged in 2022-06, with the labels that each got.

#560 Fortify 24259064: Dockerfile Misconfiguration Default User Privilege
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-560

#564 CCD-3191 to CCD-3194: Add ARGs for builder stage paths to Dockerfile
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-564

#566 CCD-3363: Whitelist prl_citizen_frontend service in case-document-am-api
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-566

#568 CCD-3387 Remove CVE Suppress Until Date from All Services
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-568
