Repository hmcts/ccd-case-document-am-api, pull requests merged in 2022-11, with the labels that each got.

#611 CCD-3885 whitelist nfdiv backend and frontend
  charts/ccd-case-document-am-api/values.yaml
  docker-compose.yml
  src/main/resources/application.yaml
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-611

#612 CCD-3917 CVE-2022-31690, CVE-2022-31690 CCD-3918 CVE-2022-42252 Suppr…
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-612

#613 Fixed invalid attribute value
  .github/workflows/dependency-check.yml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-613

#610 CCD-3802 Update to fortify-client version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-610

#609 CCD-3469 Correct Interpretations of Downstream API 5XX Responses - fi…
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/configuration/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/controller/advice/CaseDocumentControllerAdvice.java
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/security/filters/ExceptionHandlingFilter.java
  src/test/java/uk/gov/hmcts/reform/ccd/documentam/controller/advice/CaseDocumentControllerAdviceTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/documentam/security/filters/ExceptionHandlingFilterTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-609

#615 CCD-3918 CVE-2022-42252
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-615

#619 CCD-3987: Remove case security classification from search API calls.
  src/functionalTest/resources/features/common/case/Citizen_Full_Case_Creation_Data.td.json
  src/functionalTest/resources/features/common/case/Citizen_Token_Creation_Data_For_Case_Creation.td.json
  src/functionalTest/resources/features/common/case/Standard_Full_Case_Creation_Data.td.json
  src/functionalTest/resources/features/common/case/Standard_Token_Creation_Data_For_Case_Creation.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Default_Token_Creation_Data_For_Case_Creation.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation_by_solicitor_1/Befta_Jurisdiction2_Default_Full_Case_Creation_Data_solicitor_1.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation_by_solicitor_1/Befta_Jurisdiction2_Default_Token_Creation_Data_For_Case_Creation_Solicitor_1.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-citizen-case-creation/Befta_Jurisdiction2_Default_Citizen_Case_Creation_Data.td.json
  src/functionalTest/resources/features/common/case/befta-jurisdiction2-citizen-case-creation/Befta_Jurisdiction2_Default_Token_Creation_Data_For_Citizen_Case_Creation.td.json
  src/functionalTest/resources/features/common/case/befta_new/Befta_Default_Full_Case_Creation_Data.td.json
  src/functionalTest/resources/features/common/case/befta_new/Befta_Default_Token_Creation_Data_For_Case_Creation.td.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-619

#616 CCD-3917 Spring Security Upgrade
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-616

#617 CCD-3829: Add Gradle runRemoteDemo() task
  .gitignore
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-617

#620 CCD-3916 Update Github actions in workflow - master branch and on sch…
  .github/workflows/dependency-check.yml
  .github/workflows/swagger.yml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-620
