Repository hmcts/ccd-case-document-am-api, pull requests merged in 2022-08, with the labels that each got.

#588 CCD-3511 CVE-2020-15522 bouncycastle version upgraded to 1.70, suppre…
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-588

#592 Update application.yaml CCD-3597
  Jenkinsfile_CNP
  charts/ccd-case-document-am-api/values.preview.template.yaml
  src/main/resources/application.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-592

#593 Add backstage configuration file
  catalog-info.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-593
