Repository hmcts/ccd-case-document-am-api, pull requests merged in 2022-03, with the labels that each got.

#533 test definition version update to 7.13.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-533

#532 added optional caseTypeId for hashtoken calculation
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/controller/endpoints/CaseDocumentAmController.java
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/model/AuthorisedService.java
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/DocumentManagementService.java
  src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
  src/main/resources/service_config.json
  src/test/java/uk/gov/hmcts/reform/ccd/documentam/controller/endpoints/CaseDocumentAmControllerTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImplTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-532

#539 cve activities
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-539

#540 Added Employment Tribunal service
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-540

#535 Change version to 5.6.1 and remove suppression
  build.gradle
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/wiremock/extension/DynamicOAuthJwkSetResponseTransformer.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-535
