Repository hmcts/ccd-case-document-am-api, pull requests merged in 2022-12, with the labels that each got.

#623 ST_CIC service configuration
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-623

#621 CCD-4043 Fasterxml Jackson Upgrade
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-621

#624 Special Tribunals service configuration
  charts/ccd-case-document-am-api/values.yaml
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-624

#622 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-622
