Repository hmcts/ccd-case-document-am-api, pull requests merged in 2022-07, with the labels that each got.

#574 CCD-3447 : Update suppressions.xml (CVE-2022-33915)
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-574

#576 CCD-3447: CVE-2022-33915 ccd-case-document-am-api
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-576

#575 CCD-3434 upgrade Java, postgresql and redis configurations
  charts/ccd-case-document-am-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-575

#538 CCD-2496 Update all repos with multi arch base images
  Dockerfile
  acb.tpl.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-538

#570 CCD-965: Remove Temporary Sonar Exclusions ccd-case-document-am-api
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-570

#584 CCD-3512 Upgrade to latest java plugin - CVE-2022-22969 fixed upgradi…
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-584

#582 CCD-3561 Upgrade Java and Node JS versions in chart for all the respe…
  charts/ccd-case-document-am-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-582

#578 CCD-3504 Upgrade to latest java plugin - java plugin upgraded to 0.12…
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-578
