Repository hmcts/ccd-case-document-am-api, pull requests merged in 2022-04, with the labels that each got.

#543 -Adding Suppression for Spring Beans jar. Temporary Fix.
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-543

#542 spring framework version update to 5.3.15
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-542

#544 added service config for ds_ui
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-544

#545 suppress new CVE
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-545

#546 jackson.version update for CVE-2020-36518
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-546

#548 New Dates
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-548
