Repository hmcts/ccd-case-document-am-api, pull requests merged in 2023-01, with the labels that each got.

#626 CCD-4157: Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-626

#627 CCD-4163 Bump rse-gradle-java-plugin version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-627

#630 CCD-4210 CVE-2022-45143 - upgrade Tomcat to 9.0.69
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-630

#631 Update Chart.yaml
  charts/ccd-case-document-am-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-631
