Repository hmcts/ccd-case-document-am-api, pull requests merged in 2023-03, with the labels that each got.

#639 Update .terraform-version
  infrastructure/.terraform-version
Labels: ns:ccd, prd:ccd, add-or-update, rel:ccd-case-document-am-api-pr-639

#641 update befta-fw version to 8.7.11
  build.gradle
  src/test/java/uk/gov/hmcts/reform/ccd/documentam/security/SecurityUtilsTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-641

#642 CCD-4398 Upgrade dependencies to resolve CVE-2023-24998
  build.gradle
  charts/ccd-case-document-am-api/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-642

#647 CCD-4476 : changed reform-api-docs to cnp-api-docs
  .github/workflows/swagger.yml
  README.md
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-647

#643 CCD-4443: Added UPDATE permission for Probate
  src/main/resources/service_config.json
Labels: ns:ccd, prd:ccd, keep-helm, rel:ccd-case-document-am-api-pr-643
