Repository hmcts/ccd-case-document-am-api, pull requests merged in 2024-10, with the labels that each got.

#704 CCD-4604:
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-704

#697 CCD-5158 Fix CVE-2023-46589
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-697

#709 CCD-5265 : Remove suppression
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-709

#710 tidy up suppressions
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-710

#711 enable functional test reports in pipeline
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-711
