Repository hmcts/ccd-case-document-am-api, pull requests merged in 2024-08, with the labels that each got.

#694 enable fortify failure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-694

#698 fix nightly
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-698

#700 Fix nightly
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-700

#701 CCD-5159:
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-701

#702 Revert "CCD-5159:"
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-702
