Repository hmcts/ccd-case-document-am-api, pull requests merged in 2025-01, with the labels that each got.

#716 CCD-4975:
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-716

#712 CCD-5923 : Fix CVE-2023-35116
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-712

#719 CME-310: Update azurerm
  infrastructure/state.tf
Labels: ns:ccd, prd:ccd, aat/no-changes, prod/no-changes, rel:ccd-case-document-am-api-pr-719

#703 CCD-5159
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-703

#717 CCD-4373:
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-717

#721 CCD-6098 update cache to v4
  .github/workflows/dependency-check.yml
  .github/workflows/swagger.yml
Labels: ns:ccd, prd:ccd, rel:ccd-case-document-am-api-pr-721
